### ISSUE TITLE
Unable to access download for TWIM Extract

### ISSUE THREAD

**Issue by jrmattice** [RuotoloLab/TWIMExtract#1]
Hello,

I would like to use TWIM Extract as a way to access TWIM ATD from ion mobility data and estimate the conformational broadening parameter. I filled out the google form, but the link is giving me an error.
I have attached a screenshot.

Thank you,
Jenna Mattice
![TWIMExtract Error](https://user-images.githubusercontent.com/100537365/156021848-57681454-06e2-464b-8b74-2398035cae67.PNG)

**Comment by RuotoloLab** [comment]
Jenna, 

Apologies for the delay in response! The download will be added right away to GitHub as a release! :)
